import React from 'react';
import './home.css';


const Home = () => {
  return (
     <ul>
      <li>Feature 1: Responsive Design</li>
      <li>Feature 2: Easy Navigation</li>
      <li>Feature 3: Modern UI</li>
      <li>Feature 1: Responsive Design</li>
      <li>Feature 2: Easy Navigation</li>
      <li>Feature 3: Modern UI</li>
      <li>Feature 1: Responsive Design</li>
      <li>Feature 2: Easy Navigation</li>
      <li>Feature 3: Modern UI</li>
      <li>Feature 1: Responsive Design</li>
      <li>Feature 2: Easy Navigation</li>
      <li>Feature 3: Modern UI</li>
      <li>Feature 1: Responsive Design</li>
      <li>Feature 2: Easy Navigation</li>
      <li>Feature 3: Modern UI</li>
      <li>Feature 1: Responsive Design</li>
      <li>Feature 2: Easy Navigation</li>
      <li>Feature 3: Modern UI</li>
      <li>Feature 1: Responsive Design</li>
      <li>Feature 2: Easy Navigation</li>
      <li>Feature 3: Modern UI</li>
        <li>Feature 1: Responsive Design</li>
      <li>Feature 2: Easy Navigation</li>
      <li>Feature 3: Modern UI</li>
      <li>Feature 1: Responsive Design</li>
      <li>Feature 2: Easy Navigation</li>
      <li>Feature 3: Modern UI</li>
      <li>Feature 1: Responsive Design</li>
      <li>Feature 2: Easy Navigation</li>
      <li>Feature 3: Modern UI</li>
      <li>Feature 1: Responsive Design</li>
      <li>Feature 2: Easy Navigation</li>
      <li>Feature 3: Modern UI</li>
      <li>Feature 1: Responsive Design</li>
      <li>Feature 2: Easy Navigation</li>
      <li>Feature 3: Modern UI</li>
      <li>Feature 1: Responsive Design</li>
      <li>Feature 2: Easy Navigation</li>
      <li>Feature 3: Modern UI</li>
      <li>Feature 1: Responsive Design</li>
      <li>Feature 2: Easy Navigation</li>
      <li>Feature 3: Modern UI</li>
        <li>Feature 1: Responsive Design</li>
      <li>Feature 2: Easy Navigation</li>
      <li>Feature 3: Modern UI</li>
      <li>Feature 1: Responsive Design</li>
      <li>Feature 2: Easy Navigation</li>
      <li>Feature 3: Modern UI</li>
      <li>Feature 1: Responsive Design</li>
      <li>Feature 2: Easy Navigation</li>
      <li>Feature 3: Modern UI</li>
      <li>Feature 1: Responsive Design</li>
      <li>Feature 2: Easy Navigation</li>
      <li>Feature 3: Modern UI</li>
      <li>Feature 1: Responsive Design</li>
      <li>Feature 2: Easy Navigation</li>
      <li>Feature 3: Modern UI</li>
      <li>Feature 1: Responsive Design</li>
      <li>Feature 2: Easy Navigation</li>
      <li>Feature 3: Modern UI</li>
      <li>Feature 1: Responsive Design</li>
      <li>Feature 2: Easy Navigation</li>
      <li>Feature 3: Modern UI</li>
        <li>Feature 1: Responsive Design</li>
      <li>Feature 2: Easy Navigation</li>
      <li>Feature 3: Modern UI</li>
      <li>Feature 1: Responsive Design</li>
      <li>Feature 2: Easy Navigation</li>
      <li>Feature 3: Modern UI</li>
      <li>Feature 1: Responsive Design</li>
      <li>Feature 2: Easy Navigation</li>
      <li>Feature 3: Modern UI</li>
      <li>Feature 1: Responsive Design</li>
      <li>Feature 2: Easy Navigation</li>
      <li>Feature 3: Modern UI</li>
      <li>Feature 1: Responsive Design</li>
      <li>Feature 2: Easy Navigation</li>
      <li>Feature 3: Modern UI</li>
      <li>Feature 1: Responsive Design</li>
      <li>Feature 2: Easy Navigation</li>
      <li>Feature 3: Modern UI</li>
      <li>Feature 1: Responsive Design</li>
      <li>Feature 2: Easy Navigation</li>
      <li>Feature 3: Modern UI</li>
        <li>Feature 1: Responsive Design</li>
      <li>Feature 2: Easy Navigation</li>
      <li>Feature 3: Modern UI</li>
      <li>Feature 1: Responsive Design</li>
      <li>Feature 2: Easy Navigation</li>
      <li>Feature 3: Modern UI</li>
      <li>Feature 1: Responsive Design</li>
      <li>Feature 2: Easy Navigation</li>
      <li>Feature 3: Modern UI</li>
      <li>Feature 1: Responsive Design</li>
      <li>Feature 2: Easy Navigation</li>
      <li>Feature 3: Modern UI</li>
      <li>Feature 1: Responsive Design</li>
      <li>Feature 2: Easy Navigation</li>
      <li>Feature 3: Modern UI</li>
      <li>Feature 1: Responsive Design</li>
      <li>Feature 2: Easy Navigation</li>
      <li>Feature 3: Modern UI</li>
      <li>Feature 1: Responsive Design</li>
      <li>Feature 2: Easy Navigation</li>
      <li>Feature 3: Modern UI</li>
      <li>Feature 2: Easy Navigation</li>
      <li>Feature 3: Modern UI</li>
      <li>Feature 1: Responsive Design</li>
      <li>Feature 2: Easy Navigation</li>
      <li>Feature 3: Modern UI</li>
      <li>Feature 1: Responsive Design</li>
      <li>Feature 2: Easy Navigation</li>
      <li>Feature 3: Modern UI</li>
      <li>Feature 1: Responsive Design</li>
      <li>Feature 2: Easy Navigation</li>
      <li>Feature 3: Modern UI</li>
      <li>Feature 1: Responsive Design</li>
      <li>Feature 2: Easy Navigation</li>
      <li>Feature 3: Modern UI</li>
      <li>Feature 1: Responsive Design</li>
      <li>Feature 2: Easy Navigation</li>
      <li>Feature 3: Modern UI</li>
      <li>Feature 2: Easy Navigation</li>
      <li>Feature 3: Modern UI</li>
      <li>Feature 1: Responsive Design</li>
      <li>Feature 2: Easy Navigation</li>
      <li>Feature 3: Modern UI</li>
      <li>Feature 1: Responsive Design</li>
      <li>Feature 2: Easy Navigation</li>
      <li>Feature 3: Modern UI</li>
      <li>Feature 1: Responsive Design</li>
      <li>Feature 2: Easy Navigation</li>
      <li>Feature 3: Modern UI</li>
      <li>Feature 1: Responsive Design</li>
      <li>Feature 2: Easy Navigation</li>
      <li>Feature 3: Modern UI</li>
      <li>Feature 1: Responsive Design</li>
      <li>Feature 2: Easy Navigation</li>
      <li>Feature 3: Modern UI</li>
      <li>Feature 2: Easy Navigation</li>
      <li>Feature 3: Modern UI</li>
      <li>Feature 1: Responsive Design</li>
      <li>Feature 2: Easy Navigation</li>
      <li>Feature 3: Modern UI</li>
      <li>Feature 1: Responsive Design</li>
      <li>Feature 2: Easy Navigation</li>
      <li>Feature 3: Modern UI</li>
      <li>Feature 1: Responsive Design</li>
      <li>Feature 2: Easy Navigation</li>
      <li>Feature 3: Modern UI</li>
      <li>Feature 1: Responsive Design</li>
      <li>Feature 2: Easy Navigation</li>
      <li>Feature 3: Modern UI</li>
      <li>Feature 1: Responsive Design</li>
      <li>Feature 2: Easy Navigation</li>
      <li>Feature 3: Modern UI</li>
      <li>Feature 2: Easy Navigation</li>
      <li>Feature 3: Modern UI</li>
      <li>Feature 1: Responsive Design</li>
      <li>Feature 2: Easy Navigation</li>
      <li>Feature 3: Modern UI</li>
      <li>Feature 1: Responsive Design</li>
      <li>Feature 2: Easy Navigation</li>
      <li>Feature 3: Modern UI</li>
      <li>Feature 1: Responsive Design</li>
      <li>Feature 2: Easy Navigation</li>
      <li>Feature 3: Modern UI</li>
      <li>Feature 1: Responsive Design</li>
      <li>Feature 2: Easy Navigation</li>
      <li>Feature 3: Modern UI</li>
      <li>Feature 1: Responsive Design</li>
      <li>Feature 2: Easy Navigation</li>
      <li>Feature 3: Modern UI</li>
     </ul>
  );
};

export default Home;